### PR TITLE
Replace deprecated ugettext_lazy with ugettext_lazy

### PR DESCRIPTION
**Pull request by 13hakta**
Enhances compatibility with recent Django versions

PR for issue [https://github.com/GrappleGQL/wagtail-grapple/issues/201](url)

### CODE REVIEW

**Comment by zerolab** [comment]
Thank you @13hakta, there's a linting issue - https://github.com/GrappleGQL/wagtail-grapple/runs/4180136509?check_suite_focus=true
we use `pre-commit` to aid with linting, if that's easier for you

**Comment by 13hakta** [comment]
Updated and local pre-commit gone all green.

**Comment by 13hakta** [comment]
Why docs build still fail?

**Comment by zerolab** [comment]
Not sure, but it is not related to your changes.

Thank you for these, they LGTM

**Pull request merged**
